
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": null,
 "dirty": false,
 "error": "no suitable tags",
 "full-revisionid": "6534b6419c1ad0a1d98cbf0fcb59fcccd04c5675",
 "version": "0+unknown"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
